### ISSUE TITLE
React

### ISSUE THREAD

**Issue by Security2431** [webjs-tech/personal-development-plan#1]
Good to know:
- [ ] React Virtual DOM, Reconciliation and Fiber Reconciler https://namansaxena-official.medium.com/react-virtual-dom-reconciliation-and-fiber-reconciler-cd33ceb0478e
- [ ] How react works https://incepter.github.io/how-react-works/docs/react-dom/how.hooks.work/
- [ ] Pros and cons React https://www.knowledgehut.com/blog/web-development/pros-and-cons-of-react#pros%C2%A0
- [ ] List virtualization https://gusruss89.medium.com/super-simple-list-virtualization-in-react-with-intersectionobserver-ca340fe98a34
- [ ] ❗ Patterns https://soshace.com/rendering-patterns-static-and-dynamic-rendering-in-nextjs/

![Image](https://github.com/webjs-tech/personal-development-plan/assets/11134693/0ed7de38-570b-4d43-8bfa-0d059563bf37)

TODO:
- [ ] #71
- [ ] Virtual dom

**Comment by Security2431** [comment]
Top 75 questions about React:


![Image](https://github.com/webjs-tech/personal-development-plan/assets/11134693/b6a56772-9baa-4a13-b6e2-d174df73bc0d)
![Image](https://github.com/webjs-tech/personal-development-plan/assets/11134693/74aa91aa-02ea-46a2-aaaa-e1341698caaf)
![Image](https://github.com/webjs-tech/personal-development-plan/assets/11134693/63ff5f21-6788-4a4b-b54d-6232b0294c9f)
![Image](https://github.com/webjs-tech/personal-development-plan/assets/11134693/ad06a188-550d-483e-b424-60740c4bb4d1)
![Image](https://github.com/webjs-tech/personal-development-plan/assets/11134693/5cfffff3-72ec-4b1e-95dc-3a43e9cea777)
![Image](https://github.com/webjs-tech/personal-development-plan/assets/11134693/e62dffd8-d8ab-46f1-9789-0c847fca6e0f)
![Image](https://github.com/webjs-tech/personal-development-plan/assets/11134693/985ae4f8-e2f1-4815-8a97-344110d86472)
![Image](https://github.com/webjs-tech/personal-development-plan/assets/11134693/7cd2e718-368e-4bd1-920d-b55d387c1d9c)
![Image](https://github.com/webjs-tech/personal-development-plan/assets/11134693/2b0b4518-3a01-47bb-8524-372cf4440e12)
![Image](https://github.com/webjs-tech/personal-development-plan/assets/11134693/9ffb0d97-f833-45b9-86be-061679ee9f47)
![Image](https://github.com/webjs-tech/personal-development-plan/assets/11134693/4dfff6a8-f23c-4dcd-8f27-d56927d3ef3e)
![Image](https://github.com/webjs-tech/personal-development-plan/assets/11134693/a6ed962e-3cc8-4cb1-84ea-770ebb26bb2c)
![Image](https://github.com/webjs-tech/personal-development-plan/assets/11134693/c1c1a3d2-ea31-49e8-88f3-19d92b2db8d9)
![Image](https://github.com/webjs-tech/personal-development-plan/assets/11134693/6aac5f45-a01a-4997-b943-6d9bcd164f73)

**Comment by Security2431** [comment]
React interview questions:

![Image](https://github.com/webjs-tech/personal-development-plan/assets/11134693/e8f94502-9c2f-4965-82a9-739e384380ec)
![Image](https://github.com/webjs-tech/personal-development-plan/assets/11134693/98bb2b51-da37-4324-87d1-f015b3dca181)
![Image](https://github.com/webjs-tech/personal-development-plan/assets/11134693/d5bf4241-5f17-4312-8e05-88d2136deb86)
![Image](https://github.com/webjs-tech/personal-development-plan/assets/11134693/899ebf32-5cc9-4404-b84f-87cd9955cf6a)
![Image](https://github.com/webjs-tech/personal-development-plan/assets/11134693/91c3b1a2-df3a-444b-854b-2b10e4e20ddc)
![Image](https://github.com/webjs-tech/personal-development-plan/assets/11134693/09b737ed-585f-468a-b2a1-ca94a3323490)
![Image](https://github.com/webjs-tech/personal-development-plan/assets/11134693/81333f4a-b60e-453c-bda4-f48319a93e11)
![Image](https://github.com/webjs-tech/personal-development-plan/assets/11134693/d262152e-0a64-4c4a-b0ce-606d84c444b0)
![Image](https://github.com/webjs-tech/personal-development-plan/assets/11134693/63c1d196-b849-4035-97c7-76c0a0852a97)
![Image](https://github.com/webjs-tech/personal-development-plan/assets/11134693/04321096-b82b-4c3f-8534-d1425a849594)
![Image](https://github.com/webjs-tech/personal-development-plan/assets/11134693/c93aaba4-3a4e-4279-b0a5-e279003eb84d)
![Image](https://github.com/webjs-tech/personal-development-plan/assets/11134693/07a039a9-5915-4ace-af92-7a1cb81db7b5)
![Image](https://github.com/webjs-tech/personal-development-plan/assets/11134693/276466af-ce7c-4f7b-9d9e-75ee5284118a)

![Image](https://github.com/webjs-tech/personal-development-plan/assets/11134693/54c7636f-6462-47a9-8b64-6d9ee5d1bf0e)
![Image](https://github.com/webjs-tech/personal-development-plan/assets/11134693/c9c8e126-c34e-4cf8-a89e-8738547554eb)
![Image](https://github.com/webjs-tech/personal-development-plan/assets/11134693/872e8555-ed2f-4bd9-a23b-d3736d67f0b4)

**Comment by Security2431** [comment]
Interview questions React:
https://www.freecodecamp.org/news/react-interview-prep-handbook/
