### ISSUE TITLE
Typescript

### ISSUE THREAD

**Issue by Security2431** [webjs-tech/personal-development-plan#11]
Good to know:
- [ ] All features in JS and TS for last 3 years https://betterprogramming.pub/all-javascript-and-typescript-features-of-the-last-3-years-629c57e73e42
- [ ] any, unknown, never https://rahuulmiishra.medium.com/typescripts-any-vs-unknown-vs-never-when-and-how-to-use-them-35d81ea57c01
- [ ] void vs never https://phuoc.ng/collection/this-vs-that/void-vs-never/
- [ ] Typescript deep dive https://basarat.gitbook.io/typescript/future-javascript/rest-parameters

TODO:
- [ ] Utility Types
