### ISSUE TITLE
Software Development Methodology

### ISSUE THREAD

**Issue by Security2431** [webjs-tech/personal-development-plan#14]
Good to know:
- [ ] https://www.youtube.com/@ScrumMastered
- [ ] Comparing methodologies https://www.edvantis.com/blog/software-development-methodologies/

![Image](https://github.com/webjs-tech/personal-development-plan/assets/11134693/7aa1df91-efb2-4eb4-b901-de3cccf1b2a0)

TODO:
## Waterflow
- [ ] Waterflow principes

## Scrum
- [ ] Scrum flow
- [ ] What to do on first steps providing this methodology
- [ ] How to create user stories
- [ ] How to estimate
- [ ] Scrum metrics

## XP
- [ ] XP flow

## RAD
- [ ] RAD flow

## Other frameworks for big team 
- [ ] nexus
- [ ] safe
- [ ] less
