### ISSUE TITLE
Web3

### ISSUE THREAD

**Issue by Security2431** [webjs-tech/personal-development-plan#21]
Good to know:
- [ ] Blockchain https://github.com/alexromanov/awesome-blockchain-testing
- [ ] File upload https://ankr.hashnode.dev/easily-understand-and-upload-files-to-ipfs-with-filebase
- [ ] See his activity section https://hashnode.com/@codingwithmanny
- [ ] tRPC Sign In with ether https://codingwithmanny.hashnode.dev/build-a-trpc-sign-in-with-ethereum-monorepo
- [ ] SSX DAO APP https://blog.developerdao.com/getting-started-with-ssx#heading-what-is-ssx
- [ ] DAPP https://ankr.hashnode.dev/web3-data-challenges-and-the-state-of-apis
- [ ] How to start Web 3.0 path https://www.blockchain-council.org/web-3/how-to-start-a-career-in-web3/#

TODO:
- [ ] Rust
- [ ] Solana
- [ ] Smart Contract
