### ISSUE TITLE
Design Patterns

### ISSUE THREAD

**Issue by Security2431** [webjs-tech/personal-development-plan#3]
Good to know:
- [ ] Design patterns https://refactoring.guru/uk/design-patterns/typescript
- [ ] Quick guide Design Patterns in JS https://blog.carlosrojas.dev/quick-reference-guide-to-design-patterns-in-js-1ebeb1e1c605
- [ ] Design patterns for humans https://github.com/kamranahmedse/design-patterns-for-humans
- [ ] Design patterns https://refactoring.guru/design-patterns/typescript
- [ ] 9 Design Patterns everyone should know https://medium.com/frontend-canteen/9-design-patterns-every-engineer-should-know-f2423d36d468#2f95
- [ ] ❗ React Design patterns https://www.patterns.dev/vanilla/observer-pattern
- [ ] Visitor design pattern https://nkrkn.me/writing/visitor-pattern
- [ ] ❗ Frontend patterns https://javascriptpatterns.vercel.app/patterns/react-patterns/render-props
- [ ] Leetcode patterns https://blog.algomaster.io/
- [ ] Design patterns https://github.com/sudheerj/design-patterns

![Image](https://github.com/webjs-tech/personal-development-plan/assets/11134693/8088ae95-6f50-4896-9272-b180f54b09ff)

![Image](https://github.com/webjs-tech/personal-development-plan/assets/11134693/9e710c8f-2e1c-4766-83e6-913385b0dc47)

### Dependencies

- #31 
- #32 
- #33

**Comment by Security2431** [comment]
![Image](https://github.com/webjs-tech/personal-development-plan/assets/11134693/63a54e54-901d-4566-92f0-67d5624346e4)

**Comment by Security2431** [comment]
![Image](https://github.com/user-attachments/assets/da4b91e9-495c-4193-a15a-5e947b0f0a93)
