### ISSUE TITLE
Perfomance

### ISSUE THREAD

**Issue by Security2431** [webjs-tech/personal-development-plan#34]
Good to know:
- [ ] Increased SPA in 2 times https://habr.com/ru/articles/732406/
- [ ] Context optimizing https://tanmaythole.medium.com/optimizing-re-render-in-react-context-d823e113a45d
- [ ] React Profiler https://legacy.reactjs.org/blog/2018/09/10/introducing-the-react-profiler.html#ranked-chart

TODO:
- [ ] Throttling
- [ ] Debouncing
- [ ] Infinite scroll
