### ISSUE TITLE
State managers

### ISSUE THREAD

**Issue by Security2431** [webjs-tech/personal-development-plan#4]
Good to know:
- [ ] Top 20 state managers https://www.youtube.com/watch?v=P95DuIBwnqw
- [ ] Recoil https://habr.com/ru/articles/656839/

TODO:
- [ ] #84
- [ ] Reactive (Effector)
- [ ] Atomic (Jotai)
- [x] #83
- [ ] Bi-directional (MobX)
- [ ] API+ (React Router, React Query, Appolo-Client, React Hook Form)
- [ ] React Hooks (useState, useReducer, useEffect, useMemo, FSM)
- [ ] Recoil (Experimental ReactJS state management)
