### ISSUE TITLE
API Design

### ISSUE THREAD

**Issue by Security2431** [webjs-tech/personal-development-plan#43]
Good to know:
- [ ] Api architecture https://www.mparticle.com/blog/apis-vs-webhooks/
- [ ] API best practice https://www.linkedin.com/pulse/api-design-patterns-best-practices-building-robust-apis/
- [ ] Secure enpoints https://www.pixelmatters.com/blog/building-api-endpoints
- [ ] System design concept https://levelup.gitconnected.com/6-system-design-interview-concepts-1b1882506766
- [ ] ❗ 101 design api https://levelup.gitconnected.com/api-design-101-from-basics-to-best-practices-a0261cdf8886
- [ ] ❗ Versioning https://stackoverflow.blog/2020/03/02/best-practices-for-rest-api-design/

TODO:
- [ ] #96
- [ ] GraphQL
- [ ] tRPC
- [ ] gRPC
- [ ] WebSocket
- [ ] WebRTC Api

Additional Information:

![Image](https://github.com/webjs-tech/personal-development-plan/assets/11134693/639ae9dd-8c09-4389-b09f-541edb96bd69)

![Image](https://github.com/webjs-tech/personal-development-plan/assets/11134693/36e5f2d4-1a44-4c09-932c-6f9be06a24ef)

![Image](https://github.com/webjs-tech/personal-development-plan/assets/11134693/2fb23910-3aca-49e9-a756-85afe0fa5e7c)

**Comment by Security2431** [comment]
![Image](https://github.com/webjs-tech/personal-development-plan/assets/11134693/ed062b5a-2817-4ec5-a9b1-a3164885800d)

**Comment by Security2431** [comment]
![Image](https://github.com/webjs-tech/personal-development-plan/assets/11134693/c432a337-f41b-41b7-85ee-8fcd60b8145c)

**Comment by Security2431** [comment]
𝗛𝗼𝘄 𝗱𝗼 𝗛𝗧𝗧𝗣 𝘀𝘁𝗮𝘁𝘂𝘀 𝗰𝗼𝗱𝗲𝘀 𝘄𝗼𝗿𝗸, 𝗮𝗻𝗱 𝘄𝗵𝗶𝗰𝗵 𝗮𝗿𝗲 𝗺𝗼𝘀𝘁 𝗶𝗺𝗽𝗼𝗿𝘁𝗮𝗻𝘁?

When a server receives a request from a client, it provides a response that includes both the requested data and a 3-digit 𝘀𝘁𝗮𝘁𝘂𝘀 𝗰𝗼𝗱𝗲 that succinctly 𝗰𝗼𝗺𝗺𝘂𝗻𝗶𝗰𝗮𝘁𝗲𝘀 𝘁𝗵𝗲 𝗿𝗲𝗾𝘂𝗲𝘀𝘁'𝘀 𝗼𝘂𝘁𝗰𝗼𝗺𝗲 𝗼𝗿 𝘀𝘁𝗮𝘁𝘂𝘀.

Clients use these standardized sets of codes to determine if a request has been properly handled, whether more action is required, or whether an error has occurred.

HTTP status codes are 𝗱𝗶𝘃𝗶𝗱𝗲𝗱 𝗶𝗻𝘁𝗼 𝗳𝗶𝘃𝗲 𝗰𝗮𝘁𝗲𝗴𝗼𝗿𝗶𝗲𝘀, each 𝗶𝗱𝗲𝗻𝘁𝗶𝗳𝗶𝗲𝗱 𝗯𝘆 𝘁𝗵𝗲 𝗳𝗶𝗿𝘀𝘁 𝗱𝗶𝗴𝗶𝘁 𝗼𝗳 𝘁𝗵𝗲 𝗰𝗼𝗱𝗲:

🟣 𝗜𝗻𝗳𝗼𝗿𝗺𝗮𝘁𝗶𝗼𝗻𝗮𝗹 (𝟭𝘅𝘅): The request was received, and the process is continuing.
🟢 𝗦𝘂𝗰𝗰𝗲𝘀𝘀 (𝟮𝘅𝘅): The request was successfully received, understood, and accepted.
🔵 𝗥𝗲𝗱𝗶𝗿𝗲𝗰𝘁𝗶𝗼𝗻 (𝟯𝘅𝘅): The request needs further action to be completed.
🟠 𝗖𝗹𝗶𝗲𝗻𝘁 𝗲𝗿𝗿𝗼𝗿 (𝟰𝘅𝘅): The request contains incorrect syntax or cannot be fulfilled by the server.
🔴 𝗦𝗲𝗿𝘃𝗲𝗿 𝗲𝗿𝗿𝗼𝗿 (𝟱𝘅𝘅): The server failed to fulfil a valid request.

You can learn more about status codes here: https://lnkd.in/gDq8fMDt

𝗧𝗵𝗲 𝗺𝗼𝘀𝘁 𝗶𝗺𝗽𝗼𝗿𝘁𝗮𝗻𝘁/𝗰𝗼𝗺𝗺𝗼𝗻 𝗳𝗼𝗿 𝗲𝗮𝗰𝗵 𝗰𝗮𝘁𝗲𝗴𝗼𝗿𝘆 𝗮𝗿𝗲 𝗹𝗶𝘀𝘁𝗲𝗱 𝗶𝗻 𝘁𝗵𝗲 𝘃𝗶𝘀𝘂𝗮𝗹 𝗯𝗲𝗹𝗼𝘄.

Server 𝘀𝘁𝗮𝘁𝘂𝘀 𝗰𝗼𝗱𝗲𝘀 for HTTP 𝘀𝗲𝗿𝘃𝗲 𝘀𝗲𝘃𝗲𝗿𝗮𝗹 𝗸𝗲𝘆 𝗳𝘂𝗻𝗰𝘁𝗶𝗼𝗻𝘀 in web development including:

🔸 Efficient communication
🔸 Reliability and troubleshooting
🔸 Error identification
🔸 Facilitating automation
🔸 Providing user feedback
🔸 And much more…

Below are some 𝗯𝗲𝘀𝘁 𝗽𝗿𝗮𝗰𝘁𝗶𝗰𝗲𝘀 𝗳𝗼𝗿 𝘄𝗼𝗿𝗸𝗶𝗻𝗴 𝘄𝗶𝘁𝗵 𝘀𝘁𝗮𝘁𝘂𝘀 𝗰𝗼𝗱𝗲𝘀:
 
🔹 𝗨𝘀𝗲 𝘀𝗽𝗲𝗰𝗶𝗳𝗶𝗰 𝘀𝘁𝗮𝘁𝘂𝘀 𝗰𝗼𝗱𝗲𝘀: Use the most specific status code that accurately describes the outcome of an operation.
🔹 𝗕𝗲 𝗰𝗼𝗻𝘀𝗶𝘀𝘁𝗲𝗻𝘁: Maintain consistency in how you use status codes across your application.
🔹 𝗜𝗺𝗽𝗹𝗲𝗺𝗲𝗻𝘁 𝗰𝘂𝘀𝘁𝗼𝗺 𝗲𝗿𝗿𝗼𝗿 𝗺𝗲𝘀𝘀𝗮𝗴𝗲𝘀: Send additional info in the response body or headers to provide more context.
🔹 𝗟𝗼𝗴 𝗮𝗻𝗱 𝗺𝗼𝗻𝗶𝘁𝗼𝗿: Logging and monitoring of the status codes your app is sending and receiving can help in performance tuning, detecting anomalies, and debugging.

Although HTTP status codes may seem like a small and simple aspect of web development, they play an indispensable role in client, server communication. Understanding and utilizing the status codes effectively is a fundamental part of developing sound applications.

~~
A big thank you to our partner Kickresume who keeps our content free to the community.

📄 Build a winning resume (without spending all day). Kickresume has templates used by people hired at Google, Microsoft, and more (industry-specific & ATS-friendly).



![Image](https://github.com/webjs-tech/personal-development-plan/assets/11134693/7e284b5b-fa7e-4dde-8c9e-8f327898e091)
