### ISSUE TITLE
HR

### ISSUE THREAD

**Issue by Security2431** [webjs-tech/personal-development-plan#45]
Good to know:
-[ ] Поведінкове інтерв'ю [структуроване інтерв'ю] методика STAR | CleverStaff https://cleverstaff.net/blog/uk/intervyu-za-kompetentsiyamy/
- [ ] Інтерв'ю по компетенціям https://www.linkedin.com/pulse/%D1%96%D0%BD%D1%82%D0%B5%D1%80%D0%B2%D1%8E-%D0%BF%D0%BE-%D0%BA%D0%BE%D0%BC%D0%BF%D0%B5%D1%82%D0%B5%D0%BD%D1%86%D1%96%D1%8F%D1%85-%D1%89%D0%BE-%D0%BE%D1%87%D1%96%D0%BA%D1%83%D0%B2%D0%B0%D1%82%D0%B8-%D1%82%D0%B0-%D1%8F%D0%BA-%D0%BA%D0%B0%D0%BD%D0%B4%D0%B8%D0%B4%D0%B0%D1%82%D0%B0%D0%BC-smertina/
- [ ] Необхідні компетенції, їх розшифровка та питання [Criteria_eBook_SkillsoftheFuture (1).pdf](https://github.com/webjs-tech/personal-development-plan/files/13669025/Criteria_eBook_SkillsoftheFuture.1.pdf)

The list of questions:
- [ ] Як ви розумієте, що ваша робота/код виконана якісно в довгостроковій перспективі?
- [ ] Які невдачі або помилки траплялися у вас на попередній роботі та що ви робили? 
- [ ] Розкажіть про ситуацію, коли ви не виконали певну обіцянку або завдання. Що ви зробили, щоб виправити ситуацію? - [ ] Чому так сталось? Як вирішили б цю ситуацію зараз? Які результати для себе винесли?
- [ ] Розкажіть, про ситуації про роботу та комунікацію зі складним клієнтом. В чому полягала складність? Як ви працювали з цим клієнтом? Які результати принесла ця співпраця?
- [ ] Як вирішували ситуацію, коли клієнт очевидно не правий, і просить зробити в один спосіб, а ви розумієте, що клієнту краще запропонувати інше рішення, що може зекономити клієнту гроші?
- [ ] Розкажіть про ситуацію, коли вам довелося приймати важке рішення на проекті. Яка була ваша зона відповідальності? Які ще були ролі? Хто вам у цьому допомагав? Якого ви досягли результату?
- [ ] Як ви відноситеся до того, якщо на вас асайнять задачу з зони відповідальності іншого спеціаліста (іншого розробника/ПМ)? Чи були такі ситауції? В чому була причина?

**Comment by Security2431** [comment]
![Image](https://github.com/webjs-tech/personal-development-plan/assets/11134693/788d4525-16ca-4383-bb94-6a96841df5fb)
![Image](https://github.com/webjs-tech/personal-development-plan/assets/11134693/0f2b8214-eb7a-4050-9de4-41040b9ce4c7)
![Image](https://github.com/webjs-tech/personal-development-plan/assets/11134693/09288ced-293f-4a8a-bcd7-0a26da9efc46)
![Image](https://github.com/webjs-tech/personal-development-plan/assets/11134693/18be9b61-ac15-4397-b0a8-6573ce05f281)


![Image](https://github.com/webjs-tech/personal-development-plan/assets/11134693/fd1150f1-25dd-4cc1-9899-97524f884a24)



![Image](https://github.com/webjs-tech/personal-development-plan/assets/11134693/edf9a883-45c1-47dd-988e-0cc966466471)



![Image](https://github.com/webjs-tech/personal-development-plan/assets/11134693/6adcf00c-cc3c-42d7-8773-644abe23f188)



![Image](https://github.com/webjs-tech/personal-development-plan/assets/11134693/8499745c-31e7-474a-890d-98267dab2c23)



![Image](https://github.com/webjs-tech/personal-development-plan/assets/11134693/343d9869-923f-46dd-9e28-fa1bd7548db5)



![Image](https://github.com/webjs-tech/personal-development-plan/assets/11134693/5f9d18e9-3435-4e7f-a662-ed87081be372)



![Image](https://github.com/webjs-tech/personal-development-plan/assets/11134693/08b977eb-3d97-40ec-b42e-262eb48ddbc1)



![Image](https://github.com/webjs-tech/personal-development-plan/assets/11134693/ef95362f-7d13-4517-913c-65ade1476abd)



![Image](https://github.com/webjs-tech/personal-development-plan/assets/11134693/e52dfba5-9220-4ce3-ae9c-262eb875a370)



![Image](https://github.com/webjs-tech/personal-development-plan/assets/11134693/7b56c33d-b771-4173-a5cc-d0baec9349e6)



![Image](https://github.com/webjs-tech/personal-development-plan/assets/11134693/32e01139-79ea-42b2-a3fa-25e61bf336a4)



![Image](https://github.com/webjs-tech/personal-development-plan/assets/11134693/61df99fe-ab7b-403f-88a3-875d4fd42d85)



![Image](https://github.com/webjs-tech/personal-development-plan/assets/11134693/a7510645-4be6-4f4c-9b46-44751130c682)

**Comment by Security2431** [comment]
![Image](https://github.com/webjs-tech/personal-development-plan/assets/11134693/c5f97baa-75a8-49ab-b218-2df795df08ed)



![Image](https://github.com/webjs-tech/personal-development-plan/assets/11134693/9937eb1e-adc6-4dbd-922d-70ca31bff0a7)



![Image](https://github.com/webjs-tech/personal-development-plan/assets/11134693/41777858-3b86-4154-9860-32bcda08254f)



![Image](https://github.com/webjs-tech/personal-development-plan/assets/11134693/e52c4da5-eae8-4beb-b008-e01139ea196d)



![Image](https://github.com/webjs-tech/personal-development-plan/assets/11134693/080b7e29-e14e-47d1-b8b2-e8a63ad7f8c9)



![Image](https://github.com/webjs-tech/personal-development-plan/assets/11134693/13de8dad-7a1d-4adf-a388-4713cb0d3c46)



![Image](https://github.com/webjs-tech/personal-development-plan/assets/11134693/a2c2273b-a20f-4171-b493-ac8f43e14c8c)



![Image](https://github.com/webjs-tech/personal-development-plan/assets/11134693/823a3316-c7f0-4e3a-b023-121857ea6109)



![Image](https://github.com/webjs-tech/personal-development-plan/assets/11134693/9f0f93e0-125e-44d1-afed-98eb3b12ebff)



![Image](https://github.com/webjs-tech/personal-development-plan/assets/11134693/5de9b578-dd39-4169-b538-07f159d9ebde)



![Image](https://github.com/webjs-tech/personal-development-plan/assets/11134693/8757b742-e98d-4766-bfc9-741a1c10e56a)



![Image](https://github.com/webjs-tech/personal-development-plan/assets/11134693/0e3d3756-bf91-4375-accf-c4c4fdaab87c)



![Image](https://github.com/webjs-tech/personal-development-plan/assets/11134693/01f39489-17ed-4e53-831f-449b9afcba9f)



![Image](https://github.com/webjs-tech/personal-development-plan/assets/11134693/0440bff5-e1f3-423a-81ae-a9549fe562a2)



![Image](https://github.com/webjs-tech/personal-development-plan/assets/11134693/4d458001-f2b4-4d48-858b-985cb235be8e)



![Image](https://github.com/webjs-tech/personal-development-plan/assets/11134693/7ba5d5e6-7c52-45ce-b610-b9cdca8fe864)



![Image](https://github.com/webjs-tech/personal-development-plan/assets/11134693/86ea4c96-c88a-4582-a8e8-4c9442954550)



![Image](https://github.com/webjs-tech/personal-development-plan/assets/11134693/40c76576-1a97-4b63-bf6c-c12c1a8ff5f5)



![Image](https://github.com/webjs-tech/personal-development-plan/assets/11134693/7c4a7307-f7b9-4cb3-a368-96b41f7a35fa)



![Image](https://github.com/webjs-tech/personal-development-plan/assets/11134693/d247b99d-30d7-4373-829f-2fa320fc592c)



![Image](https://github.com/webjs-tech/personal-development-plan/assets/11134693/12fcd9c2-b768-426f-b474-cfd86a2870e3)



![Image](https://github.com/webjs-tech/personal-development-plan/assets/11134693/d54627d3-1e13-49cf-8e8b-580f1804c9de)
