### ISSUE TITLE
Startup

### ISSUE THREAD

**Issue by Security2431** [webjs-tech/personal-development-plan#67]
Good to know:
- [ ] Architecture of modern startup https://betterprogramming.pub/architecture-of-modern-startup-abaec235c2eb
- [ ] MVP for investors https://merge.rocks/materials/how-to-build-an-mvp
- [ ] Scaling online business https://www.ranktracker.com/uk/blog/5-ways-to-ensure-scaling-of-your-online-business/
- [ ] Project stages: Idea, MVP, Growth, Establishment
- [ ] Make a Concept, Analyze competitors, MVP, Monitize, Team(designer, dev, sell), get out asap of valley of death
- [ ] red ocean and blue ocean
- [ ] Top 3 startup mistakes https://dev.to/_michaellin/3-engineering-mistakes-that-kill-startups-3fm3
- [ ] How to start monorepo https://www.pixelmatters.com/blog/how-to-manage-multiple-front-end-projects-with-a-monorepo

![Image](https://github.com/webjs-tech/personal-development-plan/assets/11134693/41c5b0f8-67a1-47e1-8fcc-4161f9d9c86f)

![Image](https://github.com/webjs-tech/personal-development-plan/assets/11134693/d04bb15a-d92e-46b6-9e9b-2e3e9e984b93)

**Comment by Security2431** [comment]
In the last 10 years, over 1000 thousand people have asked me how to start a business.

The truth? They’re all paralyzed by limiting beliefs.

What they are and how to break them today:

Before we get into the How, let’s first unpack why people think they can’t start a business.

Here are the biggest reasons I’ve found:

Lack of Clarity

It’s hard to believe if you have no idea what the hell you’re doing.

You need some idea of what services to offer, what path to follow, and what goals to set. Stuck? Join communities, read books, and connect with weapons. 

Lack of clarity = lack of inspiration.

Overcomplicate Getting Started

The only thing you need to start a business?

1. Product/service solving a pain point
2. Paying customer

Forget the LLC, tax return, website, and logo. Until you have your first customer, that’s nothing but procrastination.

Perfectionism Paralysis

The #1 thing I see holding wantrepreneurs back? Perfectionism.

They need the perfect logo, perfect offer, perfect website, and perfect product. No wonder they never get anywhere. 

Get going, then get good. Done > perfect.

Perceived Funding Requirements

It’s crazy how many people think you need VC or a rich family to start a business — especially today.

You can hire overseas, access an army of digital robots for free, and use AI.

You don’t need funding. You need creativity.

Picking a Hard Business

Elon Musk said: “Running a start-up is like chewing glass and staring into the abyss.” Why make the journey any harder?

Pick something you enjoy with low capital/labor requirements and high leverage. 

The journey is hard enough as it is.

How to prove they can start a business:

We’ve gone over the reasons people can’t start a business.

Now, how do you actually prove you can do it?

Let’s get into it (Hint: it doesn’t come from shouting affirmations in front of your mirror):

Find Exciting Ideas

I wouldn’t be where I am if I didn’t love what I did.

I found my Ikigai - the intersection of what I love, what I’m good at, what the world needs, and what I can be paid for.

I help founders reach $5M/year with proven systems and I love every second of it.

Ship Fast and Iterate

The best entrepreneurs ship FAST. They ship. Get feedback. Iterate. Relentlessly.

Wantrepreneurs wait for the perfect idea, keep perfecting their product, and never ship.

Result? They don’t prove anything to anyone. Don’t be a wantrepreneur.

Leverage Systems

Systems separate the great entrepreneurs from the mediocre ones. 

I have systems for everything - content creation, hiring, managing - you name it, I have a system for it.

The result? $8M/year on autopilot.

I don’t believe in hustle. I believe in systems.

![Image](https://github.com/webjs-tech/personal-development-plan/assets/11134693/e0f04dab-1b8e-4015-91a2-5993dc9ddaf0)

**Comment by Security2431** [comment]
З чого починати, коли команда тільки зібралась?
Перші кроки команди, коли отримали інформацію про те, яким буде проект, над яким вони будуть працювати, але ще нічого немає:

💻 Розробники
• Вивчають технічне завдання та визначають ключові вимоги до проекту.
• Обговорюють та уточненюють технічні деталі і можливі ризики.
• Планують архітектурні сесії для обговорення загальної структури системи.
• Домовляються про стек
• Домовляються про стандарти кодування
• Домовляються про процедури перевірки
• Налаштовують середовище розробки
• Налаштовують тестове середовище
• Налаштовують продакшн
• Налаштовують CI/CD
• Розробляють стратегію безпеки та Complience
• Розробляють план резервного копіювання та відновлення

✅ Тестувальники
• Розробляють стратегію тестування, яка включає в себе методології, інструменти та плани.
• Готують тест кейси
• Готують тест сценарії
• Готують середовище тестування (testrail, або щось інше)
• Готують пристрої або емулятори для тестування
• Домовляються про критерії успішності для кожного етапу тестування.


🖼 Дизайнери
• Створюють юзер персона (портрет користувача)
• Досліджують конкурентів
• Вивчають необхідні методичні матеріали по цій ніші (бест практики, тощо)
• Починають створювати Style Guide / Дизайн-Систему
• Починають створювати іконки, інфографіку, підбирають шрифти
• Починають створювати перші мокапи та прототипи

👨‍💼 РМ
• Проводить оцінку ресурсів, та потреби в додаткових чи резервних ресурсах
• Готує проджект чартер
• Готує план комунікації
• Готує план спринтів та ретроспектив
• Готує Scope of Work розбитий на майлстоуни
• Готує діаграму Гантта
• Готує матрицю ризиків
• Готує матрицю стейкхолдерів
• Призначає ролі та обов'язки в команді
• Готує засоби комунікації (Слак/Телеграм/Діскорд, тощо)
• Готує інструменти трекінгу задач (джира/трелло/ноушн/асана, тощо)
• Готує епіки та юзер сторі
• Розробляє бізнес-процеси команди та командну документацію (як створюються, наповнюються, узгоджуються, пріоритезуються, беруться в роботу, тестуються та релізяться задачі)

💥 Ось, скільки є підготовчої роботи, доки основна робота ще не почалась!

P.S. Шановні колеги проектні менеджери, не забувайте закладати час на ці процеси в ваш роадмап)

**Comment by Security2431** [comment]
Чому класні люди йдуть з компанії та що з цим робити? 🚶

Попри війну, у кожної людини є своя межа, коли вона скаже «досить», і тоді їй уже все одно, знайде вона роботу, чи ні. Щоб цього не сталося, потрібно щоденно розвивати компанію та працювати над HR-функцією.

Зі свого досвіду я підготував найчастіші причини, чому люди звільняються та як з цим працювати:

1) Money, money, money 💵

Банально, але факт. Гроші — базова потреба людини, а хто запевняє у зворотному та навʼязує почуття провини — маніпулятор. Фінанси — інструмент, який допомагає людині втілити свої мрії у життя та самореалізуватися.

💊 Що з цим робити?
✅ Відповідати тенденціям ринку, а якщо немає можливості зробити підвищення, то чесно про це говорити (відкритість — рушійна сила, яку часто недооцінюють);
✅ Робити регулярні Performance Review, та якщо є обʼєктивні причини, чому людина не заслуговує підвищення — ставити плани розвитку з чіткими критеріями перегляду мотивації.

2) Відсутність розвитку та перспективи 🙀

Якщо людина не отримує нового професійного досвіду та бачить туманні перспективи свого майбутнього, вона шукає інші варіанти.

💊 Що з цим робити?
✅ Впровадити систему менторства, де за кожним співробітником буде закріплений ментор по Hard & Soft Skills з персональним планом розвитку. Альтернатива — система карт посад, де співробітник оцінює себе та отримує фідбек ментора згідно з очікуваними результатами посади та рекомендаціями щодо їх покращення;
✅ Робити окремі плани розвитку для C-Level Managers (якщо компетенція співробітників стає вищою за керівників, вони йдуть);
✅ Проводити регулярні воркшопи;
✅ Інформувати щодо планів розвитку компанії (які цілі ставимо та в які терміни плануємо туди прийти).

3) Відсутність двостороннього зворотного звʼязку 👥

Якщо співробітники та керівники не отримують фідбек щодо своєї роботи, починаються зайві домисли та сповільнюється розвиток з обох сторін. Це вказує на відсутність відкритості у компанії.

💊 Що з цим робити?
✅ Проводити регулярні 1х1-сесії та анонімні e-NPS опитування, щоб виявити такі речі;
✅ Ввести анонімну форму, де співробітник може відкрито сказати про проблеми;
✅ Давати можливість команді ставити незручні питання;
✅ Робити опитувальники щодо проведених активностей;
✅ Закріплювати за кожним ментора.

4) Конфлікти та токсичність 🐍

Будь-яка людина не зможе довго працювати в токсичному середовищі (навіть за всі гроші світу). Рекомендації нижче допоможуть зробити компанію екологічнішою, але як я люблю казати, все завжди йде зверху, з цінностей власників 😉

💊 Що з цим робити?
✅ Прописати цінності компанії, та брати тільки тих людей, які їм відповідають;
✅ Провести ротацію команди та звільнити токсиків;
✅ Впровадити «етичний комітет», де будуть вирішуватись конфліктні ситуації за принципом медіації;
✅ Проводити регулярні 1х1 для виявлення конфліктів;
✅ Найняти корпоративного психолога (за наявності бюджету).

**Comment by Security2431** [comment]
Пенсійний вік в Україні приблизно 60 років. Можливо вам зараз 30-35-40 років і ви розмірковуючи про майбутні професійні можливості вже починаєте тривожитися, що умовно сорокарічний вік перешкодить вам мати певну посаду чи професійний розвиток. Але ж між 40 і 60 роками 20 років. Вдумайтеся. Цілих 20 років. Це більше, ніж народження, дитинство і всі наші шкільні роки. Подумайте скільки ви всього зробили, досягли, навчилися, освоїли, пройшли за 20 років між 20 і 40 роками. Багато людей у сорокарічному віці вже мають закриті базові потреби, налагоджений ритм життя, освіту, багато різних навичок, більше часу, більше дисципліни, а значить і більше простору для кращого професійного розвитку чи змін.

Досить багато професіоналів вважають, що наступні 20 років після сорокаріччя не зовсім сприятливі для професійного розвитку та кар'єри. Хоча:

за 20 років можна побудувати сильний бізнес
за 20 років можна освоїти не одну професію
за 20 років можна вивчити не одну іноземну мову
за 20 років можна змінити спосіб життя
за 20 років можна отримати наукові відкриття та здобутки
можна знайти нові інтереси
познайомитися з новими людьми
пожити у багатьох країнах
попрацювати не в одній компанії
принести користь багатьом людям.

Цей список можна доповнити ще багатьма пунктами, які не дадуть зневіритися, а допоможуть тримати фокус уваги на позитивному та ресурсному.

Тільки ж наша тривожність змушує нас зупинитися і поринути у стан "мені вже ось стільки років".

Складіть для себе свій список що можна зробити за 20 років. А потім ще за 20 років. А потім ще за 20 років. Якщо такий список скласти важко, зверніться до коуча, ментора, колеги чи до людини, якій довіряєте.

Вік може бути ресурсом, яким варто правильно розпоряджатися.

**Comment by Security2431** [comment]
![Image](https://github.com/webjs-tech/personal-development-plan/assets/11134693/c090d9f1-6b23-4e35-9443-2fe0b12a775a)
![Image](https://github.com/webjs-tech/personal-development-plan/assets/11134693/255d8039-a5d0-4a29-ab0d-191a63fa1752)

![Image](https://github.com/webjs-tech/personal-development-plan/assets/11134693/c656867f-72d1-454a-bc72-b1b800977705)
