### ISSUE TITLE
Find Full Time Job

### ISSUE THREAD

**Issue by Security2431** [webjs-tech/personal-development-plan#79]
## Job Hunting Resources
- [ ] EnhanCV https://app.enhancv.com/find-jobs
- [ ] SnupHunt https://snaphunt.com/job-listing/all-locations/Remote/
- [ ] Turing https://developers.turing.com/dashboard/turing_test
- [ ] 🔝 Lever site:https://jobs.lever.co/ front end
- [ ] 🔝 GreenHouse site:https://boards.eu.greenhouse.io/*/jobs
- [ ] 🔝 Workable site:https://www.workable.com/
- [ ] Jobs https://startup.jobs/remote-jobs?remote=true&q=front
- [ ] Proxify https://career.proxify.io/
- [ ] HireUA https://hire.ua
- [ ] Find Remote Job https://findmyremote.ai/jobs?categories[]=frontend&search=remote&skills[]=react
- [ ] Job Scanner https://www.devjobsscanner.com/search/?search=front
- [ ] Job search https://www.get.it/
- [ ] https://nofluffjobs.com/
- [ ] https://remote.co/
- [ ] Startups https://www.workatastartup.com/companies
- [ ] Wellfound job https://wellfound.com/profile/edit
- [ ] indeed https://uk.indeed.com/jobs
- https://typescript.careers/?q=remote
- https://www.indeed.com/jobs?q=front+end&l=Remote&vjk=d89f163066250437
- https://oril.co/career/
- https://join.com/
- site:https://jobs.ashbyhq.com/
- https://agent.commit.dev
- ❗ https://jobnote.ai/

Job search:
## Preparation for interview
- [ ] Practice Tech Interview https://www.pramp.com/dashboard#/
- [ ] Practice solve tasks https://www.hackerrank.com/
- [ ] Solving JS issues https://leetcode.com/studyplan/30-days-of-javascript/
- [ ] ❗ Check, does your resume match to vacancy https://app.matchit.me/ua/my-recruiter
- [ ] 400 places to find a job https://lnkd.in/e8yT_5KT
- [ ] Generator Cover Letter https://www.grammarly.com/cover-letter
- [ ] ❗❗ Common HR questions [Digis Interview Tips – UA.pdf](https://github.com/webjs-tech/personal-development-plan/files/14251607/Digis.Interview.Tips.UA.pdf)
- [ ] ❗❗Frontend tech [React interview.pdf](https://github.com/webjs-tech/personal-development-plan/files/14261607/React.interview.pdf)
- [ ] Check your resume score https://www.kickresume.com/en/resume-checker/?utm_source=linkedin_twitter&utm_medium=socials&utm_campaign=priyank_ahuja_feb_24_checker&utm_id=priyank_ahuja_feb_24_checker
- [ ] Prepare for Frontend interview https://www.greatfrontend.com/?fpr=alexandre15&utm_source=www.hungryminds.dev&utm_medium=referral&utm_campaign=1-app-to-slice-through-front-end-interviews
- [ ] Direct contract https://dou.ua/forums/topic/49683/
- [ ] 100 interview questions https://devinterview.io/questions/web-and-mobile-development/javascript-interview-questions/

### How to find hidden jobs not posted on LinkedIn using Google?

Did you know that companies pay to advertise jobs on popular job boards or LinkedIn?
To save money, companies don’t publish all of their jobs, making it hard for you to find them.
What happens then? You can find these hidden jobs using Google Search.

Companies often use Application Tracking Systems (ATS) like Greenhouse, Workable, or Lever to post their jobs.
Search these sites for any missed opportunities.
To find jobs that are hosted on Greenhouse, type 'site:boards.greenhouse.io/* {role}' into Google.
For example, for a react developer position in Germany, type 'site:boards.greenhouse.io/* react developer in Germany'.

Search strings for other ATS:

site:apply.workable.com/* {role}
site:jobs.lever.co/* {role}
site:jobs.smartrecruiters.com/* {role}
Bonus: Additional search operators

"keyword" = Exact-match
OR = {keyword1} OR {keyword2}
AND = {keyword1} AND {keyword2}
Did you know about that method? :)

**Comment by Security2431** [comment]
![Image](https://github.com/webjs-tech/personal-development-plan/assets/11134693/bd1ae444-eb80-4e56-9b64-1d7a9f7ca467)

**Comment by Security2431** [comment]
I'm looking for a job and here's my analytics📈


Where did I start?

I created a table with columns: vacancy, date of sending, response, interview, final feedback.
What is it for?

Numbers say more than our assumptions. This way, I can track at what stage I'm slipping and what needs to be changed/corrected/re-taught.

Sometimes candidates say that they send their resumes but do not receive a response. If you get only 2-3 responses out of 100 resumes, it means that something is wrong with your resume. However, you won't know about it if you don't keep analytics.

So, during the week of active search, I submitted 19 resumes. Of these, I received 7 responses, conducted 1 test task, and received 3 offers for an interview....

This shows that I am moving in the right direction!

And tomorrow I'll tell you about my successes and failures 🙃

**Comment by Security2431** [comment]
14 HR metrics https://www.aihr.com/blog/14-hr-metrics-examples/


![Image](https://github.com/webjs-tech/personal-development-plan/assets/11134693/cd48fc92-400d-48e5-9967-5c6d65768bff)

**Comment by Security2431** [comment]
Вітаю, презентаційні
Що хоче почути роботодавець, коли запитує: "Розкажіть про себе"?

Це summary не про ваш життєвий шлях, а ваш професійний 🎓

Формула, яка допоможе скласти самопрезентацію, виглядає наступним чином:

[Descriptive word]

[your job title]

[Experience level]

[Work experience]

[Skills]

[Achievement]

За цією ж формулою до 5 речень складаєте summary і в резюме. А більш розширено готуєте для співбесіди. Звісно, що деталі про вас як особистість вітаються, але ідея не затягнути з розповіддю про хоббі на 10 хв 😁

**Comment by Security2431** [comment]
Fill up linkedin:
Пані та панове, привіт!
Зібрала ключові рекомендації для "привабливого" профілю в Лінкідін. 
Дуже корисно буде тому, хто зараз у пошуку, або ж для Junior спеціалістів - ці рекомендації допоможуть вашому профілю зібрати більше охоплень і зацікавити Рекрутерів.  😉

- Саме головне правило: Порожній профіль = Неробочий профіль.

- Фото - портрет, на якому зображені тільки ви і ніхто інший. Погляд спрямований у камеру, обличчя доброзичливе. Ніяк не фото з корпоративу, або відпочинку.
 
- Шапка профілю - Хто Ви (спеціальність), кому Ви можете бути корисні, як Ви можете допомогти, ключові слова, які найяскравіше описують вашу спеціальність.

- Краткий опис у розділі "About" - короткий стислий опис головних аспектів вашої діяльності та до чого зараз прагнете, ключові досягнення, у чому проявляється Ваша експертність.

- Професійний досвід - цей розділ має бути заповнений не поверхнево, а із зазначенням ключових моментів, яких ви досягли, поки працювали на цій посаді. Пишіть тезисно, додаючи цифри, відсотки, обсяги, найменування технологій, імена проєктів, бренди. Це все чіпляє око.

- Обкладинка - можна зробити дизайн самому під свій особистий бренд, додати графіку і вказати контакти. Або взяти заставку вашої поточної компанії, таким чином фоловери асоціюватимуть вас із брендом компанії. Дизайн робимо в Сanva або Figma, там є розділ для створення банерів LinkedIn із готових шаблонів.

- Ліцензіїі сертифікати - додавайте навчання, курси, це показує, що ви ростете професійно.

- Ключові навички (Skills & Endorsements) - це впливає на видачу вашого профілю в пошуку.

- Кастомізуйте URL свого профілю - заходимо до свого профілю/ у правому верхньому куті "Edit public profile & URL"/ на сторінці редагування акаунту у верхньому правому куті "Edit your custom URL". Краще не використовувати самобутні ніки з домашніх соцмереж. Вони завжди матимуть непрофесійний вигляд.

- Рекомендації - можна брати їх у поточних і минулих колег, клієнтів.

- Іноземні  мови - ну куди зараз без англійської. Якщо пам'ятаєте її тільки до літери G вас врятує формулювання "Limited working proficiency".

- Захоплення - сюди додаємо інфлюенсерів, компанії, групи, які відстежуєте. Показує, що у вас є свої професійні інтереси і ви щось тут взагалі читаєте. Хоча сюди рідко хто дочитує.

- Контакти - база ваших контактів будується дуже швидко, важливо тільки визначитися, який професійний контингент має входити до вашого нетворкінгу. Не варто додавати всіх підряд, як і в будь-якій мережі ви самі формуєте свою стрічку.

- И останнє. Структуруйте інформацію, використовуйте списки, суцільний текст розбивайте на абзаци.

Ці всі речі займуть у вас 30 хвилин вашого часу,але який результат 🔥

**Comment by Security2431** [comment]
Stop wasting your time searching for jobs on LinkedIn.

These 15 Websites can help you land a dream job in 30 days:

1. [Kickresume](https://www.linkedin.com/company/kickresume-com/)

Create a polished resume quickly using AI and customizable templates.

https://kickresume.com/en/

2. [Careerflow.ai](https://www.linkedin.com/company/careerflow123/)

Customize your resume to each job description, get detailed analysis and review, and never worry about optimizing it again.

3. TheJobForMe

Receive Tailored Job Suggestions.

Discover over 100,000 dream careers. Begin your journey in just 2 minutes.

https://thejobforme.com/

4. Authentic Jobs

An asset for web professionals, serving clients ranging from The New York Times to Apple and Tesla.

http://authenticjobs.com/

5. FlexJobs - Vetted Remote & Flexible Jobs

You can discover remote job opportunities nearby or across the globe.

https://www.flexjobs.com/


6. Wellfound

Where startups and job seekers intersect.

Offering 150K Tech Jobs and 27K companies.

https://wellfound.com/

7. Hubstaff Talents

Renowned for its high-quality remote job opportunities featuring top-tier talent.

From low hourly rates to six-figure salaries, the offerings accommodate individuals interested inside businesses as we.

http://talent.hubstaff.com/

8. Yoodli

Excel in your online meeting job interviews through private, real-time speech coaching. Enhance communication skills in a judgment-free environment.

https://app.yoodli.ai/

9. Metaview

AI-powered notetaker that generates perfect interview notes. It extracts topics, you choose what to include, and it writes the paragraph for you.

https://metaview.ai/

10. FinalScout

Extract valid email addresses from LinkedIn with ChatGPT, ensuring up to 98% email deliverability.

https://finalscout.com/

11. Engage AI:

Save hours crafting comments and stand out to potential job prospects. Offers touchpoints for quicker conversions.

https://engage-ai.co/


12. Jobscan

JobScan assists in optimizing your resume for any job, emphasizing the essential experience and skills that recruiters seek.

https://jobscan.co/

13. JobHunnt AI

Accelerate your hiring process with an AI-powered Job Application Assistant.

https://jobhunnt.com/

14. Interviewsby AI

Secure your dream job with personalized mock interviews for real-time feedback.

https://interviewsby.ai/

15. [Aragon.ai](http://aragon.ai/)

Transform your selfies into professional headshots.

https://www.aragon.ai/

I hope that this will definitely help you.

Do share your thoughts in the comments below.

**Comment by Security2431** [comment]
![Image](https://github.com/webjs-tech/personal-development-plan/assets/11134693/dc30fe21-6b24-46ae-805a-bfe5b3bc0fef)

**Comment by Security2431** [comment]
![Image](https://github.com/webjs-tech/personal-development-plan/assets/11134693/bafe4771-5614-46fb-8eeb-e9e8edc3a47e)

**Comment by Security2431** [comment]
![Image](https://github.com/webjs-tech/personal-development-plan/assets/11134693/46dde33c-be1c-4cef-84a2-eef93fc1eb5c)

**Comment by Security2431** [comment]
![Image](https://github.com/webjs-tech/personal-development-plan/assets/11134693/2a39c9c9-3b1f-4131-b5f3-b5784bcd743a)

**Comment by Security2431** [comment]
70 toughest interview questions:


[1709229989533.pdf](https://github.com/webjs-tech/personal-development-plan/files/14692090/1709229989533.pdf)
