### ISSUE TITLE
Algoritms and data structure

### ISSUE THREAD

**Issue by Security2431** [webjs-tech/personal-development-plan#8]
Good to know:
- [ ] From zero to hero algoritms and data structure https://dou.ua/forums/topic/40645/
- [ ] Roadmap https://neetcode.io/roadmap
- [ ] Data structure and algoritms https://github.com/sudheerj/datastructures-algorithms?tab=readme-ov-file
