### ISSUE TITLE
Promise

### ISSUE THREAD

**Issue by Security2431** [webjs-tech/personal-development-plan#9]
- [ ] new Promise
- [ ] Promise status (pending, fulfiled, rejected)
- [ ] Promise methods (Promise.all, Promise.allSettled, etc)
- [ ] Promise .then(), .catch(), .finally()
- [ ] Syntax sugar async, await
